apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hydra-vj-mixer

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - hpa.yaml  # Uncomment if you want autoscaling

images:
  - name: hydra-vj-mixer
    newTag: latest

commonLabels:
  app: hydra
  version: v1.0.0

namespace: hydra